version: '3'
services:

  mongodb:
    image: library/mongo:latest
    container_name: mongodb-tourist
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}