server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_TOURIST_USERNAME}:${MONGO_TOURIST_PASSWORD}@${MONGO_TOURIST_HOSTANAME}:${MONGO_TOURIST_PORT}/${MONGO_TOURIST_DB_NAME}?authSource=admin